package com.lourenco.backend.model;

public enum TipoNotificacao {
    NOVO_PEDIDO,
    PEDIDO_CONFIRMADO,
    PEDIDO_EM_PREPARACAO,
    PEDIDO_PRONTO,
    PEDIDO_ENTREGUE,
    PEDIDO_CANCELADO,
    NOVA_ENCOMENDA,
    ENCOMENDA_ORCAMENTO_ENVIADO,
    ENCOMENDA_APROVADA,
    ENCOMENDA_EM_PRODUCAO,
    ENCOMENDA_PRONTA,
    ENCOMENDA_ENTREGUE,
    SISTEMA
}
